### PR TITLE
Update RealmS.podspec

### PR DESCRIPTION
**Pull request by Maxim-Inv**

### CODE REVIEW

**Comment by at-daonv** [comment]
@Maxim-Inv Sorry but this PR doesn't pass CI. Please update Podfile.lock to sync with new podspec.

**Review by at-daonguyen — CHANGES_REQUESTED** [review]
@Maxim-Inv Sorry but this PR doesn't pass CI. Please update Podfile.lock to sync with new podspec.

**Comment by Maxim-Inv** [comment]
Fixed

**Comment by zendobk** [comment]
@Maxim-Inv Thanks you for contributing. I'll update more info before public new version.

**Pull request merged**
